# fly.toml app configuration file generated for updater on 2024-05-21T15:59:14+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'updater'
primary_region = 'lhr'

[build]
  [build.args]
    GO_VERSION = '1.23'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
